### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by ehab180hb** [NaturalCycles/js-lib#11]
Details:
@naturalcycles/js-lib/dist/decorators/createPromiseDecorator.js:59
                    cfg.finallyFn?.(resp);
                                           ^

    SyntaxError: Unexpected token '.'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (node_modules/@naturalcycles/js-lib/dist/index.js:30:34)

**Comment by kirillgroshkov** [comment]
Optional chaining requires certain Node.js version that supports it. You probably ran it on earlier version.
